spring.application.name=auth

server.port=${SERVER_PORT:8084}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/auth_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:auth_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:auth_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.idle-timeout=8000
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.max-lifetime=1000

jwt.secret=${JWT_SECRET:defaultSecretKeyForJWTTokenGenerationThatShouldBeAtLeast256BitsLongForSecurityPurposes}
jwt.expiration=86400000
